[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_8"
world_address = "0x16eda1adea730fbdc03915563ba9daff347e096e6fbb29f837705ca67db1aef"

[namespace]
default = "ls_0_0_9"

[writers]
"ls_0_0_9" = [
    "ls_0_0_9-game_systems", 
    "ls_0_0_9-game_token_systems", 
    "ls_0_0_9-settings_systems",
    "ls_0_0_9-beast_systems",
    "ls_0_0_9-adventurer_systems",
    "ls_0_0_9-objectives_systems"
]

[migration]
order_inits = [
    "ls_0_0_9-game_systems",
    "ls_0_0_9-loot_systems",
    "ls_0_0_9-renderer_systems",
    "ls_0_0_9-adventurer_systems",
    "ls_0_0_9-beast_systems",
    "ls_0_0_9-game_token_systems", 
    "ls_0_0_9-settings_systems", 
    "ls_0_0_9-objectives_systems"
]

[init_call_args]
"ls_0_0_9-game_token_systems" = [
    "0x065d2AB17338b5AffdEbAF95E2D79834B5f30Bac596fF55563c62C3c98700150", # account address
    "0x05dbee8088168034c49756aff50baae46f03ecaf0bd8b1ad7248ff0de83fafc0", # denshokan address
    "1" # Option::None for renderer address
]