[world]
name = "Loot Survivor 2"
description = "Slay The Beasts"
seed = "pg_test_ls_6"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[namespace]
default = "ls_0_0_1"

[writers]
"ls_0_0_1" = ["ls_0_0_1-game_systems", "ls_0_0_1-game_token_systems"]

[init_call_args]
"ls_0_0_1-game_token_systems" = [
    "0x0238df9Efd27Aba2ccB0bdC97a4cf440caA403e9ed3f1883294Ab6CDBA6C5282",
]