[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x3640d513d1d398f3221adcc7b038fcd3a875e85cce31014897337b7f0d0be6e"

[namespace]
default = "ls_0_0_5"

[writers]
"ls_0_0_5" = [
    "ls_0_0_5-game_systems", 
    "ls_0_0_5-game_token_systems", 
    "ls_0_0_5-settings_systems",
    "ls_0_0_5-beast_systems",
    "ls_0_0_5-adventurer_systems"
]

[init_call_args]
"ls_0_0_5-game_token_systems" = [
    "0x065d2AB17338b5AffdEbAF95E2D79834B5f30Bac596fF55563c62C3c98700150", # account address
    "0x05e0f818f368a6bc04e923541477181d6e47044549fc6f4eb0fb4c8d7da373a9" # denshokan address
]