[package]
cairo-version = "=2.9.2"
name = "lootsurvivor"
version = "1.2.2"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "=2.9.2"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.3.0" }
tournaments = { git = "https://github.com/Provable-Games/tournaments.git" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.3.0" }
starknet = "=2.9.2"
cairo_test = "=2.9.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]