world_address = "0x0036820d4ae5a7d96fa97a51da8ae27cc74b07e029941f130fa0d7980870a9a4"
rpc = "https://api.cartridge.gg/x/pg-slot/katana"

[events]
raw = true

[sql]
historical = ["ls_0_0_3-GameEvent"]

[indexing]
namespaces = ["ls_0_0_3"]
pending = true
